Blogossio/Blog/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
                       url(r'^$', 'Blog.views.home', name='home'),
                       url(r'^noticias/', 'Blog.views.noticia', name='noticias'),
                       url(r'^herramientas/', 'Blog.views.herramienta', name='herramientas'),
                       url(r'^contactos/', 'Blog.views.contacto', name='contactos'),
                       url(r'^masinformacion/', 'Blog.views.masinfo', name='masinformacion'),
                       url(r'^ver_post/(?P<id_post>[0-9]+)$', 'Blog.views.ver_post', name='posts'),
                       url(r'^save_message/$', 'Blog.views.save_message', name='save_message'),
                       url(r'^contact/$', 'Blog.views.contact', name='contact'),
                       url(r'^categoria/(?P<categoria>[0-9]+)$', 'Blog.views.categoria', name='categoria'),
                       )

Blogossio/Blogossio/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^', include('Blog.urls', namespace = "blog_bossio")),
    url(r'^admin/', include(admin.site.urls)),
]

Blogossio/Blog/models.py
# -*- coding: utf-8 -*-
from django.db import models

# Create your models here.


class Categoria(models.Model):
    titulo_txt = models.CharField('Titulo', max_length=20)
    def __str__(self):
        return self.titulo_txt

class Post(models.Model):
    class Meta:
        ordering=['-fecha_pub']
    
    titulo_txt = models.CharField('Titulo', max_length=20)
    fecha_pub = models.DateTimeField('date published', auto_now_add=True)
    txt_resumen = models.CharField('Resumen', max_length=50)
    txt_cont = models.TextField('Contenido')
    categoria = models.ForeignKey(Categoria)
    
    def __str__(self):
        return self.titulo_txt
                                
class Coment(models.Model):
    fecha_pub = models.DateTimeField('date published', auto_now_add=True)
    titulo_txt = models.CharField('Titulo del Comentario', max_length=20)
    coment_txt = models.TextField('Comentatrio', max_length=100)
    published = models.BooleanField(u'Publicado?', default=True)
    post = models.ForeignKey(Post)
    def __str__(self):
        return self.titulo_txt

Blogossio/Blog/views.py
from django.shortcuts import render
from django.template import RequestContext
from django.shortcuts import render_to_response, render, redirect
from Blog.models import Post, Coment, Categoria
from django.core.mail import send_mail

def home(request):
    context = RequestContext(request)
    categorias = Categoria.objects.all()
    posts = Post.objects.all()
    coments = Coment.objects.all()
    return render_to_response('home.html',
                              {'posts':posts, 'coments':coments, 'categorias':categorias},
                              context)
def contacto(request):
    context = RequestContext(request)
    return render_to_response('contacto.html',
                              {'posts':None},
                              context)
def noticia(request):
    context = RequestContext(request)
    return render_to_response('noticias.html',
                              {'posts':None},
                              context)
def herramienta(request):
    context = RequestContext(request)
    return render_to_response('herramientas.html',
                              {'posts':None},
                              context)
def masinfo(request):
    context = RequestContext(request)
    return render_to_response('masinfo.html',
                              {'posts':None},
                              context)
def ver_post(request, id_post):
    context = RequestContext(request)
    post = Post.objects.get(id=id_post)
    coments = Coment.objects.filter(post=post, published = True)
    return render_to_response('posts.html', 
                              {'post':post, 'coments':coments},
                              context)
def save_message(request):
    context = RequestContext(request)
    coment_txt = None
    if request.method == 'POST':
        mi_post =               Post.objects.get(id=request.POST['id'])
        print(mi_post)
        titulo_txt= request.POST['titulo_txt']
        coment_txt= request.POST['coment_txt']        
        msje = Coment()
        msje.titulo_txt = titulo_txt
        msje.coment_txt = coment_txt
        msje.post = mi_post
        msje.save()
        coments = Coment.objects.filter(post=mi_post, published = True)

    return render_to_response('mensajes.html', 
                              {'coments':coments},
                              context)
def contact(request):
    context  = RequestContext(request)
    
    if request.method=="POST":
        nombre = request.POST["nombre"]
        emailRemit = request.POST["email"]
        mensaje = request.POST["mensaje"]
        send_mail(str(nombre), str(mensaje), emailRemit,['mateofede98@gmail.com'], fail_silently=False)
    return render_to_response("contact.html",
                             context)

def categoria(request, categoria):
    context = RequestContext(request)
    categoria = Categoria.objects.get(id=categoria)
    post = Post.objects.filter(categoria=categoria)
    return render_to_response('categoria.html', 
                              {'post':post, 'categoria':categoria},
                              context)

Blogossio/Blog/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <body>
    <nav>
    <div class="tittle">
            <h1> BOSSIOLOG</h1>
            <h2> DONDE LE AGREGAMOS BOSSIO A TODO </h2>
            </div>
            <ul id="menu">
            <li><a href="{% url 'blog_bossio:home' %}">Home</a></li>
            <li><a href="{% url 'blog_bossio:noticias' %}">Noticias</a></li>
            <li><a href="{% url 'blog_bossio:herramientas' %}">Herramientas</a></li>
            <li><a href="{% url 'blog_bossio:contactos' %}">Contacto</a></li>
            <li><a href="{% url 'blog_bossio:masinformacion' %}">Mas info</a></li>
            </ul>
            <div class="border">  
            {% block content %}

            {% endblock %}
            </div>
            <ul id="menu">
            <li><a href="{% url 'blog_bossio:home' %}">Home</a></li>
            <li><a href="{% url 'blog_bossio:noticias' %}">Noticias</a></li>
            <li><a href="{% url 'blog_bossio:herramientas' %}">Herramientas</a></li>
            <li><a href="{% url 'blog_bossio:contactos' %}">Contacto</a></li>
            <li><a href="{% url 'blog_bossio:masinformacion' %}">Mas info</a></li>
            </ul>
        </nav>
        <script src="{% static 'js/jquery-1.11.3.js' %}"></script>
        {% block scripts %}

            {% endblock %}
        
    </body>
</html>

Blogossio/Blog/templates/categoria.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}
    <h2>{{categoria.titulo_txt}}</h2>
    {% for posts in post %}
        <div class="posts">
        <h3>{{posts.titulo_txt}}</h3>
        <a href="{% url 'blog_bossio:posts' posts.id %}">Mas info</a>
        <p>{{posts.txt_resumen}}</p>
        </div>
    {% endfor %}
{% endblock%}

Blogossio/Blog/templates/contact.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% load staticfiles %}
{% block content %}
    <form id="formulario" method="post">
    {% csrf_token %}
        <h2>Contactenos</h2>
        <hr>
        <h3>Le responderemos en las proximas 48hs</h3>
        <div class="usuario">
            Nombre:
            <input id="nombre" name="nombre" type="text"/>
            Email:
            <input id="email" name="email" type="text" />
        </div>
        <div class="mensaje">
            Mensaje:
            <textarea rows="6" size="60" cols="65" name="mensaje" id="mensaje"></textarea>
        </div>
        <button id="botonEnviar" type="submit" value="Enviar">Enviar</button>
    </form>
{% endblock %}

Blogossio/Blog/templates/contacto.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}
    <h2> Contactenos </h2>
    <hr>
    <br>
    <h3> Si quiere ser todo un Bossio </h3>
    <div class="usuario">
        Nombre (+ssio) :<br>    
        <input type="text" name:"Nombre" id="name" value=""></input><br>
        Email:<br>
        <input type="text" name:"Email" id="email"></input><br>
        Asuntossio:<br>
        <input type="text" name:"Asunto" id="asunto"></input><br>
    </div>
    <div class="mensaje">
    Mensaje:<br>
    <textarea type="text" size="60" name="Email" id="mensaje" rows="6" cols="65"></textarea>
    </div>
    <div class="random">
    <button type="button" id="btn1" onmouseover="Change(this)" onclick="Mensaje()" align="right">ENVIAR</button>
    </div>
    <a href="{% url 'blog_bossio:contact'%}">Enviar un mensaje de verdad</a>
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/contacto.js' %}"></script>
{% endblock %}

Blogossio/Blog/templates/herramientas.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}
    <h2> Estas algunas herramientas de nuestra pagina </h2>
    <hr>
    <br>
    <h3> Conversor de Modnedas </h3>
    <br>
    <div class="conversordatos">
        <select id = "comboloco" class="combo">
        <option value="1">Dolar</option>
        <option value="2">Peso ARG</option>
        <option value="3">Real</option>
        <option value="4">Euro</option>
        <option value="5">Libra</option>
        <option value="6">Peso UR</option>
        <option value="7">Peso CH</option>
        </select>
        <br>
        <br>
        <select id = "comboloco2" class="combo">
        <option value="1">Dolar</option>
        <option value="2">Peso</option>
        <option value="3">Real</option>
        <option value="4">Euro</option>
        <option value="5">Libra</option>
        <option value="6">Peso UR</option>
        <option value="7">Peso CH</option>
        </select>
    </div>
    <div class="conversor">
        Monto:
        <input id="monto" type="text" value=""></p>
        Valor:   
        <input id="vuelto" type="text" value=""></p>
    </div>
    <div class="convertir">
        <button type="button" onclick="Convertir()" align= center class="botonsito" >Continuar</button>
    </div>
    <br>
    <hr>
    <br>
    <h3> La Calculadora </h3>
    <br>
    <div class="calcu">
        <input id="resultado" type="text" value="" style="width: 354px; height:60px; font-size:40px;"/>
        <br>
        <input type="button" id="btn1" onclick="ejecutar(this)" value="1" class="botones"/>
        <input type="button" id="btn2" onclick="ejecutar(this)" value="2" class="botones"/>
        <input type="button" id="btn3" onclick="ejecutar(this)" value="3" class="botones"/>
        <input type="button" id="btnmas" onclick="ejecutar(this)" value="+" class="botones"/>
        <br>
        <input type="button" id="btn4" onclick="ejecutar(this)" value="4" class="botones"/>
        <input type="button" id="btn5" onclick="ejecutar(this)" value="5" class="botones"/>
        <input type="button" id="btn6" onclick="ejecutar(this)" value="6" class="botones"/>
        <input type="button" id="btnmenos" onclick="ejecutar(this)" value="-" class="botones"/>
        <br>
        <input type="button" id="btn7" onclick="ejecutar(this)" value="7" class="botones"/>
        <input type="button" id="btn8" onclick="ejecutar(this)" value="8" class="botones"/>
        <input type="button" id="btn9" onclick="ejecutar(this)" value="9" class="botones"/>
        <input type="button" id="btnpor" onclick="ejecutar(this)" value="*" class="botones"/>
        <br>
        <input type="button" id="btnp" onclick="ejecutar(this)" value="." class="botones"/>
        <input type="button" id="btn0" onclick="ejecutar(this)" value="0" class="botones"/>
        <input type="button" id="btne" onclick="ejecutar(this)" value="=" class="botones"/>
        <input type="button" id="btndiv" onclick="ejecutar(this)" value="/" class="botones"/>
        <br>
    </div>
    <br>
    <hr>
    <br>
    <h3> El Cronometro </h3>
    <br>
    <div class="cron">
        <div id=reloj>
        00 : 00 : 00
        </div>
        <input type="button" class="botones2" id=empezar onclick=iniciar() value=Start />
        <input type="button" class="botones2" id=stop onclick=parar() value=Stop />
        <input type="button" class="botones2" id=vuelta onclick=vuelta() value=Vuelta />
        <input type="button" class="botones2" id=Reset onclick=reiniciar() value=Reset />
        <div id="vueltas">
        <h3> Vueltas: </h3>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script src="{% static 'js/herramientas.js' %}"></script>
{% endblock %}

Blogossio/Blog/templates/home.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}
    
<title>This is my page</title>
<h2> Posts Recientes </h2>
{% for post in posts %}
    <div class="posts">
    <h3>{{post.titulo_txt}}</h3>
    <a href="{% url 'blog_bossio:posts' post.id %}">Mas info</a>
    <p>{{post.txt_resumen}}</p>
    </div>
{% endfor %}
<br>
<hr>
<br>
<h2> Explorar por Categorias </h2>
{% for categoria in categorias %}
    <h3><li><a href="{% url 'blog_bossio:categoria' categoria.id %}">{{categoria.titulo_txt}}></a></li></h3>
{% endfor %}
<br>
<hr>
<br>
<h3> THE ORIGINALOSSIOS </h3>
<img ALIGN=CENTER src="{% static 'img/originalossio.png' %}" alt="Changin img" id="imagen">
<br>
<div class="progress">
    <img src="{% static 'img/progres.png' %}" name="bar"/>
</div>
<br>
<input id="%" type="text" value=""/>
<br>
<script>var ruta = "{% static 'img/' %}" </script>
<script src="{% static 'js/home.js' %}"></script>
<script src="{% static 'js/jquery-1.11.3.js' %}"></script>    

{% endblock %}

Blogossio/Blog/templates/masinfo.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}
    <H2>CURRICULUM VITAE</H2><HR>
    <h3>DATOS PERSONALES:</h3>
    <br>
    Nombre: Mateo Federico
    <br>
    Apellido: Bossio
    <br>
    Lugar de nacimiento: Cordoba 
    <br>e
    Nacimiento: 2/06/98
    <br>
    Estado civil: Soltero
    <br>
    DNI: 41264890
    <br>
    Direccion: Lascano Colodrero 2878
    <br>
    Telefono: 3513541545
    <br>
    E-mail: mateofbossio@gmail.com
    <br>
    <hr>
    <h3>FORMACION ACADEMICA:</h3>
    Primaria: Colegio Padre Claret
    <br>
    Secundario: Instituto Tecnico Salesiano Villada
    <br>
    Especiializacion: Programacion
    <br>
    <hr>
    <h3>EXPERIENCIA PROFESIONAL:</h3>
    <br>
    Tecnico Informatico de la familia
    <br>
    <hr>
    <h3>IDIOMAS:</h3>
    Espaniol
    <br>
    Ingles-5 anios
    <br>
    <hr>
    <h3>OTROS DATOS:</h3>
    Resposabilidad
    <br>
    Puntualidad
    <br>
    Respetuoso
    <br>
    <hr>
{% endblock %}

Blogossio/Blog/templates/mensajes.html
<div class="posts">
    {% for comentario in coments %}
        <h3>{{comentario.titulo_txt}}</h3>
        <h4>{{comentario.fecha_pub}}</h4>
        <p>{{comentario.coment_txt}}</p>
        <hr>
    {% endfor %}
</div>

Blogossio/Blog/templates/noticias.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}
    <h2> Las fotos de la semana: </h2>
    <img ALIGN=CENTER src="{% static 'img/grasancrem.jpg' %}" alt="Changin img" id="imagen">
    <br>
    <div class="progress">
        <img src="{% static 'img/progres.png' %}" name="bar"/>
    </div>
    <br>
    <input id="%" type="text" value="" style= background-color: transparent;/>
    <hr><H2>La Camara denego denuncia de Nisman contra Cristina</H2><hr>
    <img src="{% static 'img/cristina.jpg' %}" alt="denegan denuncia" align="center">
    <br>
    <h3>Dos de los jueces concluyeron que el memorandum con Iran no constituyo ningon delito para encubrir a los autores del ataque. El vocal Farah, a favor de la investigacion.</h3><br>
    <p>Buenos Aires. Tal como se vaticinaba, la Sala I de la Camara Federal confirmo, en voto dividido, la desestimacion de la denuncia penal del fallecido fiscal Alberto Nisman contra la presidenta Cristina Fernandez y el canciller Hector Timerman, entre otros, por presunto encubrimiento de los acusados por el atentado a la Amia mediante el memorandum de entendimiento con Iran.

Los camaristas Jorge Ballestero y Eduardo Freiler ratificaron el fallo del juez Daniel Rafecas que desecho la denuncia por inexistencia de delito, mientras que Eduardo Farah se inclino por hacer lugar a la apelacion de aquella medida efectuada por el fiscal Gerardo Pollicita.

Farah voto por iniciar una investigacion para que se hagan las medidas de prueba solicitadas por el fiscal y que se aparte al juez Rafecas por el tenor de la postura que ya asumio.</p>
    <br>
    <br>
    <nav>
        <div class="boton">
            <li><a href=http://www.lavoz.com.ar/politica/en-fallo-dividido-la-camara-denego-denuncia-de-nisman-contra-cristina>Leer mas</a></li>
        </div> 
    </nav>
    <br>
    <br>
    <hr><h2>El grupo HECATOMBE presento la secdiva a GRASANCREM.</h2><hr>
    <img src="{% static 'img/grasancrem.jpg' %}" alt="El cast de HECATOMBE">
    <br>
    <h3>El grupo cordobes lleno el Cabildo para la presentacion de su nuevo video. Anunciaron un nuevo Concierto entusiasmo, el videojuego y una obra de teatro.</h3><BR>
    <p>Volvio la pesadilla mas divertida. Volvieron los chicos de Hecatombe! Y eso es una forma de decir, ya que hace tiempo llegaron a la Web para quedarse, con una serie de videos graciosos que convirtieron al grupo en un fenomeno con mas de ocho millones de visitas.<br>
    Ayer demostraron el poder de encantamiento con el publico adolescente y juvenil, que colmo el Cabildo para el estreno de la secuela de Grasancrem, el video que les abrio las puertas al exito.<br>
    Y si, se puede hablar de secuela porque fue un video en el que dejaron a un lado el encanto del amateurismo de sus inicios para mostrar el mismo humor que los posiciono bien arriba pero con una produccion más ambiciosa.</p><br>
    <br>
    <br>
    <nav>
        <div class="boton">
            <li><a href=https://www.youtube.com/watch?v=obAMyj0Zgw8>Vea el video</a></li>
        </div> 
    </nav>
    <br>
    <br>
    <br>
    <hr><h2>Orion declaro y la AFA analiza su sancion.</h2><hr>
    <img ALIGN=CENTER src="{% static 'img/orion.jpg' %}" alt="Orion en una entrevista">
        <br>
    <br>
    <h3>El arquero estuvo poco mas de media hora en el edificio de la calle Viamonte. El miercoles proximo se conocera la pena, por su expdivsion ante San Martin de San Juan.</h3><br>
    <p>El arquero de Boca Agustin Orion se presento en la AFA para declarar, tras su expdivsion en el partido del divtimo domingo, que su equipo igualo 1-1 con San Martin en San Juan, por una dura infraccion sobre Carlos Bueno, que le produjo una fractura de tibia y perone derechos al delantero uruguayo.<br>
    El guardavalla llego a la sede que la casa matriz del futbol argentino posee en la calle Viamonte a las 19.50 y opto por el silencio, ante el requerimiento de los periodistas presentes. Treinta y cuatro minutos más tarde atraveso nuevamente la puerta blanca del edificio. Me está esperando mi esposa. Perdon, buenas noches, alcanzó a decir, antes de retirarse. Ahora debera esperar la decisión del Tribunal de Disciplina, que se conocera el miercoles proximo.<br>
    La sancion a Orion, que se encuentra suspendido provisoriamente y no podra jugar el domingo ante Estudiantes -su reemplazante sera Guillermo Sara-, se conocera la semana proxima. De acuerdo con lo establecido en los artícdivos 199 y 201 del Reglamento de Transgresiones y Penas de la AFA, le podria caber una pena de entre 2 y 30 encuentros.</p>
    <br>
    <br>
    <nav>
        <div class="boton">
            <li><a href=http://www.clarin.com/deportes/futbol/boca-juniors/Orion-declaro-AFA-analiza-sancion_0_1327667656.html>Leer mas</a></li>
        </div> 
    </nav>
    <br>
    <br>
    <br>
    <hr><h2>Espionaje en Formosa.</h2><hr>
    <img src="{% static 'img/gildo.jpg' %}" alt="Gildo el espia">
    <br>
    <br>
    <h3>En Formosa existe un aparato de espionaje montado desde lo mas alto del gobierno para informarle al mandatario provincial, Gildo Insfran, que hacen opositores, aborigenes y periodistas. Los mails de la denuncia. Un informe de Telenoche. </h3>
    <p>Si algo le faltaba a esta provincia, manejada por la misma persona desde hace 20 anos, es una denuncia por espionaje ilegal.<br>
    En los divtimos dias se filtraron doscientos correos electronicos que contienen fotografias, grabaciones y hasta informes de inteligencia realizados por la policia provincial. Desde lo mas alto del poder se espia a periodistas, a politicos opositores y tambien a aliados. Es el superagente Gildo.<br>
    Por primera vez, un policia que conoce como funciona el aparato de espionaje y de vigilancia de Insfran, cuenta lo que en Formosa todo el mundo sospecha pero nadie se anime a decir.</p>
    <br>
    <br>
    <nav>
        <div class="boton">
        <li><a href=file:http://tn.com.ar/politica/espionaje-en-formosa-asi-espia-el-superagente-gildo_579143S>Leer mas</a></li>
        </div> 
    </nav>
    </div>
{% endblock %}
{% block scripts %}
    <script>var ruta = "{% static 'img/' %}" </script>
    <script src="{% static 'js/noticias.js' %}"></script>
{% endblock %}

Blogossio/Blog/templates/posts.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}
    <div class="posts">
        <h2>{{post.titulo_txt}}</h2>
        <hr>
        <h3>{{post.txt_resumen}}</h3>
        <p>{{post.txt_cont}}</p>
    </div>
    <div class="posts">
        <h2>Comentarios</h2>
        {% csrf_token %} 
        <div id="mensajes">
            {% include "mensajes.html" %}
        </div>
        <div class="posts">
        <br>
        <br>
        <h3>Nombre:</h3>
        <br>
        <input name="nombre" type="text" style="color:black" id="name" required data-validation-required-message="Please enter your name.">
        <br>
        <br>
        <h3>Mensaje:</h3>
        <br>
        <textarea name="mensaje" rows="6" cols="60" style="color:black" id="message" required data-validation-required-message="Please enter a message."></textarea>
        <br>
        <br>
        <button id="btn_enviar" name="enviar"> Comment </button>
        </div>
    </div>
    
{% endblock %}
{% block scripts %}

<script>

    $("#btn_enviar").click(function(){        
        console.log("VAMO");
        var data={
            csrfmiddlewaretoken: '{{ csrf_token }}',
            id:'{{post.id}}',
            titulo_txt:$('#name').val(),
            coment_txt:$('#message').val(),
        }
        $.ajax({
            type: "POST",
            url: "{% url 'blog_bossio:save_message' %}",
            data: data,
            success: function(result){
                $("#mensajes").html(result);
                $("#name").val("");
                $("#message").val("");
            },
            error: function(err){
                console.log("ERRRORRRR");
                console.log(err.responseText);
            },
        });
    });
</script>


{% endblock %}